### ISSUE TITLE
Pulling messages problem

### ISSUE THREAD

**Issue by IfusaaX** [dado3212/Groupme-Saver#2]
While running the script, I get the error below. Exporting attachments and user profile pictures works fine, the most important part to export messages, unfortunately not working. I looked hours into this, but can't figure it out.

Do you know what the issue is? Error code:

Saving messages to viewer file...
a bytes-like object is required, not 'str'
Whoops

**Comment by dado3212** [comment]
Should be related to Python3.  I just added in Python3 support as well as maintaining backwards compatibility with Python2.7.  If it's still not working, please open another issue!  Thanks.
